### ISSUE TITLE
Can I write some tags on the file?

### ISSUE THREAD

**Issue by HeyLeom** [Owen-oj/laravel-getid3#11]
Hi, I need to write the tags on a mp3, wav and aiff file. tags like title, artist, bpm, artwork, etc.

**Comment by Owen-oj** [comment]
Technically, you can as this functionality is available in the underlying library [getID3](https://github.com/JamesHeinrich/getID3). However, I could add that functionality next week. You could also submit a PR if you are in a hurry.

**Comment by HeyLeom** [comment]
> Technically, you can as this functionality is available in the underlying library [getID3](https://github.com/JamesHeinrich/getID3). However, I could add that functionality next week. You could also submit a PR if you are in a hurry.

I would like to submit a PR but I'm a noob, would be great if you add that functionality, I can wait, many thanks!

**Comment by tahirafridi** [comment]
I'm here if this functionality added into your repo?
THANK YOU!
