### ISSUE TITLE
Undefined type 'Owenoj\LaravelGetId3\GetId3'.intelephense(1009)

### ISSUE THREAD

**Issue by MatMT** [Owen-oj/laravel-getid3#21]
I followed the steps but it does not seem to detect the instance of the class :(
![204044](https://user-images.githubusercontent.com/82849501/184056147-1ee04910-ae3d-40bc-a9f8-b63341578aeb.png)

**Comment by Owen-oj** [comment]
you may want to check your installation or dev environment

**Comment by MatMT** [comment]
![image](https://user-images.githubusercontent.com/82849501/184250559-47b5b7ff-2a89-469e-b2f4-d824a12249c4.png)
![image](https://user-images.githubusercontent.com/82849501/184250610-db15325a-bf31-4763-924e-e1adff7c0ec8.png)

Fine!, now i get this errors 😅🫥

**Comment by Owen-oj** [comment]
Just use this instead. 
```php
$track = GetId3::fromDiskAndPath('local', '/some/file.mp3');
```
