### ISSUE TITLE
Changing ID3 to MP3

### ISSUE THREAD

**Issue by SequelONE** [Owen-oj/laravel-getid3#8]
Hello. 
Is it possible to change the received data and save it to mp3 using PHP?

**Comment by muarachmann** [comment]
> Hello.
> Is it possible to change the received data and save it to mp3 using PHP?

Can you elaborate more on the use case? What received data?

**Comment by SequelONE** [comment]
> > Hello.
> > Is it possible to change the received data and save it to mp3 using PHP?
> 
> Can you elaborate more on the use case? What received data?

Hello.

I want to overwrite this data to an mp3 file, so that I can then download the overwritten files and upload them to the site vk.com. Where of these values automatically sets the name of the track and artist. So that you don't have to manually re-order everything.
